services:
  app:
    build: .
    image: nixerr/delivery-city:latest
    ports:
      - "3001:3001"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - GA_MEASUREMENT_ID
